#!/usr/bin/bash

rm -rfv ~/.config/GNOME-xdg-terminals.list
rm -rfv ~/.config/dconf
rm -rfv ~/.config/eog
rm -rfv ~/.config/evolution
rm -rfv ~/.config/gnome-session
rm -rfv ~/.config/goa-1.0
rm -rfv ~/.config/gtk-3.0
rm -rfv ~/.config/gtk-4.0
rm -rfv ~/.config/ibus
rm -rfv ~/.config/mimeapps.list
rm -rfv ~/.config/nautilus
rm -rfv ~/.config/pulse
rm -rfv ~/.config/shotwell
rm -rfv ~/.config/user-dirs.dirs
rm -rfv ~/.config/user-dirs.locale
rm -rfv ~/.config/xdg-terminals.list
rm -rfv ~/.cache/epiphany
rm -rfv ~/.cache/evolution
rm -rfv ~/.cache/folks
rm -rfv ~/.cache/fontconfig
rm -rfv ~/.cache/gnome-calculator
rm -rfv ~/.cache/gstreamer-1.0
rm -rfv ~/.cache/ibus
rm -rfv ~/.cache/mesa_shader_cache
rm -rfv ~/.cache/obexd
rm -rfv ~/.cache/shotwell
rm -rfv ~/.cache/thumbnails
rm -rfv ~/.cache/tracker3
rm -rfv ~/.local/share/Trash
rm -rfv ~/.local/share/applications
rm -rfv ~/.local/share/backgrounds
rm -rfv ~/.local/share/epiphany
rm -rfv ~/.local/share/evolution
rm -rfv ~/.local/share/folks
rm -rfv ~/.local/share/fonts
rm -rfv ~/.local/share/gnome-settings-daemon
rm -rfv ~/.local/share/gnome-shell
rm -rfv ~/.local/share/gvfs-metadata
rm -rfv ~/.local/share/icc
rm -rfv ~/.local/share/keyrings
rm -rfv ~/.local/share/nautilus
rm -rfv ~/.local/share/org.gnome.TextEditor
rm -rfv ~/.local/share/recently-used.xbel
rm -rfv ~/.local/share/shotwell
rm -rfv ~/.local/share/sounds
rm -rfv ~/.local/state/wireplumber
